### ISSUE TITLE
Save parent session for derived sessions

### ISSUE THREAD

**Issue by schu** [openmultiplechoice/openmultiplechoice#763]
After a session, users can repeat questions with wrong answers ("Repeat incorrect"). We collect the questions into an ephemeral deck and then create a session based on the deck. Since we don't save the parent session, we currently have no way to identify the "origin" of the derived session and ephemeral deck.

Store the parent session for derived sessions to allow us to identify derived sessions and their origin. This will also allow us to show the info to the user and make the UI and UX clearer in that regard.

**Comment by levinuss** [comment]
Implemented the backend code in #862
Should there be a `parent_session` column for (ephemeral) decks as well?
What frontend changes (info to the user) would you like to have? The id of the parent session is part of the generated deck title, should it be displayed anywhere else?

**Comment by schu** [comment]
> Implemented the backend code in https://github.com/openmultiplechoice/openmultiplechoice/pull/862

Merged, thanks!

> Should there be a `parent_session` column for (ephemeral) decks as well?

I hadn't thought about this and I think yes. Even if we don't use the data yet, it might be helpful later.

> What frontend changes (info to the user) would you like to have? The id of the parent session is part of the generated deck title, should it be displayed anywhere else?

I would like to defer that to later and maybe do it as part of a refactoring of the session UI code (session list on index page etc.)
