### ISSUE TITLE
"New session" view: subjects not sorted properly with Chrome/Chromium

### ISSUE THREAD

**Issue by schu** [openmultiplechoice/openmultiplechoice#824]
Chrome/Chromium users reported that the list of subjects in the "New session" view is not sorted.

**Comment by schu** [comment]
This could explain the issue: https://issues.chromium.org/issues/42200309

i.e. we have to return `1`, `0` or `-1`, not `true` or `false`.

https://github.com/openmultiplechoice/openmultiplechoice/blob/1deae59e96dd1745130443c9910903d2e40c965b/resources/js/NewSessionView.svelte#L35-L49

**Comment by levinuss** [comment]
> i.e. we have to return 1, 0 or -1, not true or false.

Yes, that fixed it. Submitted a PR :)
